# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/miuicamera/common/proprietary/system/etc/public.libraries-xiaomi.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-xiaomi.txt \
    vendor/xiaomi/miuicamera/common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.misys@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.misys@1.0-service.rc \
    vendor/xiaomi/miuicamera/common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.misys@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.misys@2.0-service.rc \
    vendor/xiaomi/miuicamera/common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.misys@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.misys@3.0-service.rc

PRODUCT_PACKAGES += \
    libOpenCL_system \
    libarcsoft_dualcam_refocus_system \
    libarcsoft_dualcam_refocus_front_system \
    libarcsoft_dualcam_refocus_rear_t_system \
    libarcsoft_dualcam_refocus_rear_w_system \
    libarcsoft_portrait_lighting_system \
    libarcsoft_portrait_lighting_c_system \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libdoc_photo \
    libdoc_photo_c++_shared \
    libgallery_arcsoft_dualcam_refocus \
    libgallery_arcsoft_portrait_lighting \
    libgallery_arcsoft_portrait_lighting_c \
    libgallery_mpbase \
    libmibokeh_gallery \
    libmpbase_system \
    librefocus \
    librefocus_mibokeh \
    vendor.xiaomi.hardware.misys@1.0-impl \
    vendor.xiaomi.hardware.misys@2.0-impl \
    vendor.xiaomi.hardware.misys@3.0-impl \
    libcheckpid \
    liblogwrap_vendor \
    vendor.xiaomi.hardware.misys@1.0 \
    vendor.xiaomi.hardware.misys@2.0 \
    vendor.xiaomi.hardware.misys@3.0 \
    MiuiCamera \
    MiuiExtraPhoto \
    vendor.xiaomi.hardware.misys@1.0.xml \
    vendor.xiaomi.hardware.misys@2.0.xml \
    vendor.xiaomi.hardware.misys@3.0.xml \
    vendor.xiaomi.hardware.misys@1.0-service \
    vendor.xiaomi.hardware.misys@2.0-service \
    vendor.xiaomi.hardware.misys@3.0-service

PRODUCT_PACKAGES += \
    libcamera_algoup_jni.xiaomi_libcamera_algoup_jni.xiaomi_symlink64 \
    libcamera_mianode_jni.xiaomi_libcamera_mianode_jni.xiaomi_symlink64 \
    libdoc_photo_libdoc_photo_symlink64 \
    libdoc_photo_c++_shared_libdoc_photo_c++_shared_symlink64 \
    libgallery_arcsoft_dualcam_refocus_libgallery_arcsoft_dualcam_refocus_symlink64 \
    libgallery_arcsoft_portrait_lighting_libgallery_arcsoft_portrait_lighting_symlink64 \
    libgallery_arcsoft_portrait_lighting_c_libgallery_arcsoft_portrait_lighting_c_symlink64 \
    libgallery_mpbase_libgallery_mpbase_symlink64 \
    libmibokeh_gallery_libmibokeh_gallery_symlink64 \
    librefocus_librefocus_symlink64 \
    librefocus_mibokeh_librefocus_mibokeh_symlink64
